export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const PROFILES_ID = process.env.NEXT_PUBLIC_APPWRITE_PROFILES_ID!;
export const DOCUMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_DOCUMENTS_ID!;
